server:
  port: 9090
spring:
  application:
    name: JPAapp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  logging.level.org.hibernate.type.descriptor.sql: trace
